#!/bin/sh
set -e

BOOTSTRAPPED="/etc/dovecot/.bootstrapped"

if [ ! -e $BOOTSTRAPPED ]; then
	cat <<-EOF > /etc/dovecot/dovecot-ldap.conf.ext
	hosts = $SLAPD_HOST
	auth_bind = no
	ldap_version = 3
	base = $SLAPD_SEARCH_BASE
	deref = never
	scope = subtree
	user_attrs = =home=/var/mail/%d/%n/
	user_filter = (&(objectclass=inetOrgPerson)(objectclass=inetLocalMailRecipient)(mail=%u))
	pass_attrs = mail=user,userPassword=password
	pass_filter = (&(objectclass=inetOrgPerson)(objectclass=inetLocalMailRecipient)(mail=%u))
	iterate_filter = (&(objectclass=inetOrgPerson)(objectclass=inetLocalMailRecipient))
	default_pass_scheme = CRYPT
	EOF

	touch $BOOTSTRAPPED
fi

exec dovecot -F -c /etc/dovecot/dovecot.conf