#!/bin/sh
set -e

cat <<-EOF > /etc/dovecot/dovecot.conf
protocols = imap lmtp sieve
listen = *
login_trusted_networks = $LOGIN_TRUSTED_NETWORKS
!include conf.d/*.conf
EOF

cat <<-EOF > /etc/dovecot/dovecot-ldap.conf.ext
hosts = $LDAP_HOST
auth_bind = no
dn = $LDAP_BIND_DN
dnpass = $LDAP_PASS
ldap_version = 3
base = $LDAP_BASE_DN
deref = never
scope = subtree
user_attrs = =home=/mail/%d/%n/, =uid=vmail, =gid=vmail
user_filter = (&(objectclass=inetOrgPerson)(objectclass=inetLocalMailRecipient)(mail=%u))
pass_attrs = mail=user,userPassword=password
pass_filter = (&(objectclass=inetOrgPerson)(objectclass=inetLocalMailRecipient)(mail=%u))
iterate_filter = (&(objectclass=inetOrgPerson)(objectclass=inetLocalMailRecipient))
default_pass_scheme = CRYPT
EOF

cat <<-EOF > /etc/dovecot/conf.d/15-lda.conf
lda_mailbox_autocreate = yes
protocol lda {
	mail_plugins = $mail_plugins sieve
	postmaster_address = $POSTMASTER
}
EOF

cat <<-EOF > /etc/dovecot/conf.d/20-lmtp.conf
protocol lmtp {
	mail_plugins = $mail_plugins sieve
	postmaster_address = $POSTMASTER
	hostname = $LMTP_HOSTNAME
}
EOF

crontab - <<-EOF
$CRON_EXPUNGE_TRASH /usr/local/bin/doveadm expunge -A mailbox Trash savedbefore $EXPUNGE_TRASH
$CRON_EXPUNGE_JUNK /usr/local/bin/doveadm expunge -A mailbox Junk savedbefore $EXPUNGE_JUNK
EOF

exec dovecot -F -c /etc/dovecot/dovecot.conf